// Code generated by goctl. DO NOT EDIT!
// Source: account.proto

package server

import (
	"context"

	"account/rpc/internal/logic"
	"account/rpc/internal/svc"
	"account/rpc/types/account"

	"github.com/zeromicro/go-zero/core/logx"
)

type AccountServer struct {
	svcCtx *svc.ServiceContext
	account.UnimplementedAccountServer
}

func NewAccountServer(svcCtx *svc.ServiceContext) *AccountServer {
	return &AccountServer{
		svcCtx: svcCtx,
	}
}

func (s *AccountServer) GetUserInfo(ctx context.Context, in *account.UserInfoRequest) (*account.UserInfoResponse, error) {
	l := logic.NewGetUserInfoLogic(ctx, s.svcCtx)
	logx.Info("in==",*in)
	return l.GetUserInfo(in)
}
