// Code generated by goctl. DO NOT EDIT!
// Source: account.proto

package account

import (
	"context"

	"account/rpc/types/account"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	UserInfo         = account.UserInfo
	UserInfoRequest  = account.UserInfoRequest
	UserInfoResponse = account.UserInfoResponse

	Account interface {
		GetUserInfo(ctx context.Context, in *UserInfoRequest, opts ...grpc.CallOption) (*UserInfoResponse, error)
	}

	defaultAccount struct {
		cli zrpc.Client
	}
)

func NewAccount(cli zrpc.Client) Account {
	return &defaultAccount{
		cli: cli,
	}
}

func (m *defaultAccount) GetUserInfo(ctx context.Context, in *UserInfoRequest, opts ...grpc.CallOption) (*UserInfoResponse, error) {
	client := account.NewAccountClient(m.cli.Conn())
	return client.GetUserInfo(ctx, in, opts...)
}
