// Code generated by protoc-gen-go. DO NOT EDIT.
// source: account.proto

package account

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RPC_CALL_RESULT int32

const (
	RPC_CALL_RESULT_RPC_CALL_RESULT_NONE        RPC_CALL_RESULT = 0
	RPC_CALL_RESULT_RPC_CALL_RESULT_SUCCESS     RPC_CALL_RESULT = 1
	RPC_CALL_RESULT_RPC_CALL_RESULT_DB_ERROR    RPC_CALL_RESULT = 2
	RPC_CALL_RESULT_RPC_CALL_RESULT_INPUT_ERROR RPC_CALL_RESULT = 3
	RPC_CALL_RESULT_RPC_CALL_RESULT_ERROR       RPC_CALL_RESULT = 4
)

var RPC_CALL_RESULT_name = map[int32]string{
	0: "RPC_CALL_RESULT_NONE",
	1: "RPC_CALL_RESULT_SUCCESS",
	2: "RPC_CALL_RESULT_DB_ERROR",
	3: "RPC_CALL_RESULT_INPUT_ERROR",
	4: "RPC_CALL_RESULT_ERROR",
}

var RPC_CALL_RESULT_value = map[string]int32{
	"RPC_CALL_RESULT_NONE":        0,
	"RPC_CALL_RESULT_SUCCESS":     1,
	"RPC_CALL_RESULT_DB_ERROR":    2,
	"RPC_CALL_RESULT_INPUT_ERROR": 3,
	"RPC_CALL_RESULT_ERROR":       4,
}

func (x RPC_CALL_RESULT) String() string {
	return proto.EnumName(RPC_CALL_RESULT_name, int32(x))
}

func (RPC_CALL_RESULT) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{0}
}

type UserInfoRequest struct {
	Userid               int64    `protobuf:"varint,1,opt,name=userid,proto3" json:"userid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserInfoRequest) Reset()         { *m = UserInfoRequest{} }
func (m *UserInfoRequest) String() string { return proto.CompactTextString(m) }
func (*UserInfoRequest) ProtoMessage()    {}
func (*UserInfoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{0}
}

func (m *UserInfoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserInfoRequest.Unmarshal(m, b)
}
func (m *UserInfoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserInfoRequest.Marshal(b, m, deterministic)
}
func (m *UserInfoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserInfoRequest.Merge(m, src)
}
func (m *UserInfoRequest) XXX_Size() int {
	return xxx_messageInfo_UserInfoRequest.Size(m)
}
func (m *UserInfoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UserInfoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UserInfoRequest proto.InternalMessageInfo

func (m *UserInfoRequest) GetUserid() int64 {
	if m != nil {
		return m.Userid
	}
	return 0
}

type UserInfoResponse struct {
	Result               RPC_CALL_RESULT `protobuf:"varint,1,opt,name=result,proto3,enum=account.RPC_CALL_RESULT" json:"result,omitempty"`
	Info                 *UserInfo       `protobuf:"bytes,2,opt,name=info,proto3" json:"info,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *UserInfoResponse) Reset()         { *m = UserInfoResponse{} }
func (m *UserInfoResponse) String() string { return proto.CompactTextString(m) }
func (*UserInfoResponse) ProtoMessage()    {}
func (*UserInfoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{1}
}

func (m *UserInfoResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserInfoResponse.Unmarshal(m, b)
}
func (m *UserInfoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserInfoResponse.Marshal(b, m, deterministic)
}
func (m *UserInfoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserInfoResponse.Merge(m, src)
}
func (m *UserInfoResponse) XXX_Size() int {
	return xxx_messageInfo_UserInfoResponse.Size(m)
}
func (m *UserInfoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UserInfoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UserInfoResponse proto.InternalMessageInfo

func (m *UserInfoResponse) GetResult() RPC_CALL_RESULT {
	if m != nil {
		return m.Result
	}
	return RPC_CALL_RESULT_RPC_CALL_RESULT_NONE
}

func (m *UserInfoResponse) GetInfo() *UserInfo {
	if m != nil {
		return m.Info
	}
	return nil
}

type UserInfo struct {
	Userid               int64    `protobuf:"varint,1,opt,name=userid,proto3" json:"userid,omitempty"`
	Username             string   `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Sex                  int32    `protobuf:"varint,3,opt,name=sex,proto3" json:"sex,omitempty"`
	Mood                 string   `protobuf:"bytes,4,opt,name=mood,proto3" json:"mood,omitempty"`
	City                 int32    `protobuf:"varint,5,opt,name=city,proto3" json:"city,omitempty"`
	Schoolid             int32    `protobuf:"varint,6,opt,name=schoolid,proto3" json:"schoolid,omitempty"`
	Status               int32    `protobuf:"varint,7,opt,name=status,proto3" json:"status,omitempty"`
	RegTime              string   `protobuf:"bytes,8,opt,name=regTime,proto3" json:"regTime,omitempty"`
	Phone                string   `protobuf:"bytes,9,opt,name=phone,proto3" json:"phone,omitempty"`
	Email                string   `protobuf:"bytes,10,opt,name=email,proto3" json:"email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserInfo) Reset()         { *m = UserInfo{} }
func (m *UserInfo) String() string { return proto.CompactTextString(m) }
func (*UserInfo) ProtoMessage()    {}
func (*UserInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{2}
}

func (m *UserInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserInfo.Unmarshal(m, b)
}
func (m *UserInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserInfo.Marshal(b, m, deterministic)
}
func (m *UserInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserInfo.Merge(m, src)
}
func (m *UserInfo) XXX_Size() int {
	return xxx_messageInfo_UserInfo.Size(m)
}
func (m *UserInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_UserInfo.DiscardUnknown(m)
}

var xxx_messageInfo_UserInfo proto.InternalMessageInfo

func (m *UserInfo) GetUserid() int64 {
	if m != nil {
		return m.Userid
	}
	return 0
}

func (m *UserInfo) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *UserInfo) GetSex() int32 {
	if m != nil {
		return m.Sex
	}
	return 0
}

func (m *UserInfo) GetMood() string {
	if m != nil {
		return m.Mood
	}
	return ""
}

func (m *UserInfo) GetCity() int32 {
	if m != nil {
		return m.City
	}
	return 0
}

func (m *UserInfo) GetSchoolid() int32 {
	if m != nil {
		return m.Schoolid
	}
	return 0
}

func (m *UserInfo) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *UserInfo) GetRegTime() string {
	if m != nil {
		return m.RegTime
	}
	return ""
}

func (m *UserInfo) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *UserInfo) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func init() {
	proto.RegisterEnum("account.RPC_CALL_RESULT", RPC_CALL_RESULT_name, RPC_CALL_RESULT_value)
	proto.RegisterType((*UserInfoRequest)(nil), "account.UserInfoRequest")
	proto.RegisterType((*UserInfoResponse)(nil), "account.UserInfoResponse")
	proto.RegisterType((*UserInfo)(nil), "account.UserInfo")
}

func init() { proto.RegisterFile("account.proto", fileDescriptor_8e28828dcb8d24f0) }

var fileDescriptor_8e28828dcb8d24f0 = []byte{
	// 384 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x92, 0xd1, 0xae, 0xd2, 0x40,
	0x10, 0x86, 0x2d, 0x2d, 0x2d, 0x0c, 0x51, 0xea, 0x04, 0x75, 0x01, 0x13, 0x09, 0x89, 0x09, 0x7a,
	0x81, 0x06, 0x9f, 0x00, 0x6a, 0x63, 0x48, 0x10, 0xc8, 0x96, 0xde, 0x78, 0xd3, 0xd4, 0xb2, 0x48,
	0x23, 0xed, 0x62, 0x77, 0x9b, 0xe8, 0xeb, 0xf8, 0x88, 0x3e, 0x81, 0xe9, 0xb6, 0xf4, 0x24, 0x3d,
	0xe7, 0xdc, 0xcd, 0xff, 0xff, 0x5f, 0xfe, 0x6e, 0x3a, 0x03, 0x4f, 0xc3, 0x28, 0xe2, 0x79, 0x2a,
	0xe7, 0xd7, 0x8c, 0x4b, 0x8e, 0x56, 0x25, 0xa7, 0xef, 0xa0, 0xef, 0x0b, 0x96, 0xad, 0xd3, 0x13,
	0xa7, 0xec, 0x57, 0xce, 0x84, 0xc4, 0x97, 0x60, 0xe6, 0x82, 0x65, 0xf1, 0x91, 0x68, 0x13, 0x6d,
	0xa6, 0xd3, 0x4a, 0x4d, 0x7f, 0x82, 0x7d, 0x87, 0x8a, 0x2b, 0x4f, 0x05, 0xc3, 0x8f, 0x60, 0x66,
	0x4c, 0xe4, 0x17, 0xa9, 0xd8, 0x67, 0x0b, 0x32, 0xbf, 0x7d, 0x87, 0xee, 0x9d, 0xc0, 0x59, 0x6e,
	0x36, 0x01, 0x75, 0x3d, 0x7f, 0x73, 0xa0, 0x15, 0x87, 0x6f, 0xc1, 0x88, 0xd3, 0x13, 0x27, 0xad,
	0x89, 0x36, 0xeb, 0x2d, 0x9e, 0xd7, 0x7c, 0x5d, 0xad, 0xe2, 0xe9, 0x3f, 0x0d, 0x3a, 0x37, 0xeb,
	0xb1, 0x17, 0xe1, 0x08, 0x3a, 0xc5, 0x94, 0x86, 0x09, 0x53, 0x7d, 0x5d, 0x5a, 0x6b, 0xb4, 0x41,
	0x17, 0xec, 0x37, 0xd1, 0x27, 0xda, 0xac, 0x4d, 0x8b, 0x11, 0x11, 0x8c, 0x84, 0xf3, 0x23, 0x31,
	0x14, 0xa9, 0xe6, 0xc2, 0x8b, 0x62, 0xf9, 0x87, 0xb4, 0x15, 0xa6, 0xe6, 0xa2, 0x55, 0x44, 0x67,
	0xce, 0x2f, 0xf1, 0x91, 0x98, 0xca, 0xaf, 0x75, 0xf1, 0x12, 0x21, 0x43, 0x99, 0x0b, 0x62, 0xa9,
	0xa4, 0x52, 0x48, 0xc0, 0xca, 0xd8, 0x8f, 0x43, 0x9c, 0x30, 0xd2, 0x51, 0xf5, 0x37, 0x89, 0x03,
	0x68, 0x5f, 0xcf, 0x3c, 0x65, 0xa4, 0xab, 0xfc, 0x52, 0x14, 0x2e, 0x4b, 0xc2, 0xf8, 0x42, 0xa0,
	0x74, 0x95, 0x78, 0xff, 0x57, 0x83, 0x7e, 0xe3, 0xbf, 0x21, 0x81, 0x41, 0xc3, 0x0a, 0xb6, 0xbb,
	0xad, 0x6b, 0x3f, 0xc1, 0x31, 0xbc, 0x6a, 0x26, 0x9e, 0xef, 0x38, 0xae, 0xe7, 0xd9, 0x1a, 0xbe,
	0x06, 0xd2, 0x0c, 0x3f, 0xaf, 0x02, 0x97, 0xd2, 0x1d, 0xb5, 0x5b, 0xf8, 0x06, 0xc6, 0xcd, 0x74,
	0xbd, 0xdd, 0xfb, 0x87, 0x0a, 0xd0, 0x71, 0x08, 0x2f, 0x9a, 0x40, 0x19, 0x19, 0x8b, 0xaf, 0x60,
	0x2d, 0xcb, 0x9d, 0xe1, 0x0a, 0x7a, 0x5f, 0x98, 0xac, 0xd7, 0x44, 0xee, 0x2f, 0xb3, 0x3c, 0xa9,
	0xd1, 0xf0, 0x81, 0xa4, 0xbc, 0xa0, 0x55, 0xef, 0x5b, 0x77, 0xfe, 0xa1, 0x4a, 0xbf, 0x9b, 0xea,
	0x3a, 0x3f, 0xfd, 0x0f, 0x00, 0x00, 0xff, 0xff, 0x34, 0xf3, 0xfb, 0xad, 0xae, 0x02, 0x00, 0x00,
}
